src/Entity/HistoriqueAchat.php
<?php

namespace App\Entity;

use App\Entity\User;
use DateTimeInterface;
use App\Entity\Produit;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HistoriqueAchatRepository")
 */
class HistoriqueAchat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;    

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="historiqueAchats")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Produit", inversedBy="historiqueAchats")
     */
    private $produit;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateAchat;

    /**
     * @ORM\Column(type="integer")
     */
    private $Quantite;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_limite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $EtatH;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->DateAchat;
    }

    public function setDateAchat(\DateTimeInterface $DateAchat): self
    {
        $this->DateAchat = $DateAchat;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->Quantite;
    }

    public function setQuantite(int $Quantite): self
    {
        $this->Quantite = $Quantite;

        return $this;
    }

    public function getDateLimite(): ?\DateTimeInterface
    {
        return $this->date_limite;
    }

    public function setDateLimite(?\DateTimeInterface $date_limite): self
    {
        $this->date_limite = $date_limite;

        return $this;
    }

    public function getEtatH(): ?string
    {
        return $this->EtatH;
    }

    public function setEtatH(?string $EtatH): self
    {
        $this->EtatH = $EtatH;

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    public $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Prix;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date_Limite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Taux_Sucre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Taux_Sel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Taux_Proteine;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Taux_Fibre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Taux_Energie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Taux_Gras;

   /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Taux_Additif;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CompoRecette", mappedBy="produit")
     */
    private $compoRecettes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\HistoriqueAchat", mappedBy="produit")
     */
    private $historiqueAchats;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $marque;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $taux_calcium;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $taux_sodium;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nutriscore_grade;

    public function __construct()
    {
        $this->historiqueAchats = new ArrayCollection();
        $this->compoRecettes = new ArrayCollection();
    }


    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(string $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getDateLimite(): ?\DateTimeInterface
    {
        return $this->Date_Limite;
    }

    public function setDateLimite(\DateTimeInterface $Date_Limite): self
    {
        $this->Date_Limite = $Date_Limite;

        return $this;
    }

    public function getTauxSucre(): ?string
    {
        return $this->Taux_Sucre;
    }

    public function setTauxSucre(?string $Taux_Sucre): self
    {
        $this->Taux_Sucre = $Taux_Sucre;

        return $this;
    }

    public function getTauxSel(): ?string
    {
        return $this->Taux_Sel;
    }

    public function setTauxSel(?string $Taux_Sel): self
    {
        $this->Taux_Sel = $Taux_Sel;

        return $this;
    }

    public function getTauxProteine(): ?string
    {
        return $this->Taux_Proteine;
    }

    public function setTauxProteine(?string $Taux_Proteine): self
    {
        $this->Taux_Proteine = $Taux_Proteine;

        return $this;
    }

    public function getTauxFibre(): ?string
    {
        return $this->Taux_Fibre;
    }

    public function setTauxFibre(?string $Taux_Fibre): self
    {
        $this->Taux_Fibre = $Taux_Fibre;

        return $this;
    }

    public function getTauxEnergie(): ?string
    {
        return $this->Taux_Energie;
    }

    public function setTauxEnergie(?string $Taux_Energie): self
    {
        $this->Taux_Energie = $Taux_Energie;

        return $this;
    }

    public function getTauxGras(): ?string
    {
        return $this->Taux_Gras;
    }

    public function setTauxGras(?string $Taux_Gras): self
    {
        $this->Taux_Gras = $Taux_Gras;

        return $this;
    }

    public function getNutriscore(): ?string
    {
        return $this->Nutriscore;
    }

    public function setNutriscore(?string $Nutriscore): self
    {
        $this->Nutriscore = $Nutriscore;

        return $this;
    }

    public function getTauxAdditif(): ?string
    {
        return $this->Taux_Additif;
    }

    public function setTauxAdditif(?string $Taux_Additif): self
    {
        $this->Taux_Additif = $Taux_Additif;

        return $this;
    }

    /**
     * @return Collection|CompoRecette[]
     */
    public function getCompoRecettes(): Collection
    {
        return $this->compoRecettes;
    }

    public function addCompoRecette(CompoRecette $compoRecette): self
    {
        if (!$this->compoRecettes->contains($compoRecette)) {
            $this->compoRecettes[] = $compoRecette;
            $compoRecette->setProduit($this);
        }

        return $this;
    }

    public function removeCompoRecette(CompoRecette $compoRecette): self
    {
        if ($this->compoRecettes->contains($compoRecette)) {
            $this->compoRecettes->removeElement($compoRecette);
            // set the owning side to null (unless already changed)
            if ($compoRecette->getProduit() === $this) {
                $compoRecette->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|HistoriqueAchat[]
     */
    public function getHistoriqueAchats(): Collection
    {
        return $this->historiqueAchats;
    }

    public function addHistoriqueAchat(HistoriqueAchat $historiqueAchat): self
    {
        if (!$this->historiqueAchats->contains($historiqueAchat)) {
            $this->historiqueAchats[] = $historiqueAchat;
            $historiqueAchat->setProduit($this);
        }

        return $this;
    }

    public function removeHistoriqueAchat(HistoriqueAchat $historiqueAchat): self
    {
        if ($this->historiqueAchats->contains($historiqueAchat)) {
            $this->historiqueAchats->removeElement($historiqueAchat);
            // set the owning side to null (unless already changed)
            if ($historiqueAchat->getProduit() === $this) {
                $historiqueAchat->setProduit(null);
            }
        }

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(?string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getTauxCalcium(): ?string
    {
        return $this->taux_calcium;
    }

    public function setTauxCalcium(?string $taux_calcium): self
    {
        $this->taux_calcium = $taux_calcium;

        return $this;
    }

    public function getTauxSodium(): ?string
    {
        return $this->taux_sodium;
    }

    public function setTauxSodium(?string $taux_sodium): self
    {
        $this->taux_sodium = $taux_sodium;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNutriscoreGrade(): ?string
    {
        return $this->nutriscore_grade;
    }

    public function setNutriscoreGrade(?string $nutriscore_grade): self
    {
        $this->nutriscore_grade = $nutriscore_grade;

        return $this;
    }

}

templates/daily_fridge/accueil.html.twig
{% extends 'base.html.twig' %}
{% block stephane %}{% endblock %} 
{% block body %}

    <br/>

     {% for Histoproduit in Histoproduits %}

       {% set nombreJour= Histoproduit.DateLimite|date("d") -  "now"|date("d") %}
        
        {% if Histoproduit.DateLimite|date("m/d/Y") < "now"|date("m/d/Y") %}

            <div class="alert alert-dismissible alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Produit périmé :  <a href="#" class="alert-link"></a> {{ Histoproduit.produit.nom }} </strong>
                dans le frigo depuis le {{ Histoproduit.DateAchat|date("m/d/Y") }}
                date limite :  {{ Histoproduit.DateLimite|date("m/d/Y") }}
            </div>

         {% elseif  (nombreJour >= 0) and (nombreJour <= 3) %}

            <div class="alert alert-dismissible alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Produit proche de la date de péremption :  <a href="#" class="alert-link"></a> {{ Histoproduit.produit.nom }} </strong>
                dans le frigo depuis le {{ Histoproduit.DateAchat|date("m/d/Y") }}
                date limite :  {{ Histoproduit.DateLimite|date("m/d/Y") }}
            </div>
         
        {% endif %}



    {% endfor %}


    

<h1>MyDailyFridge : les bons choix pour votre frigo !</h1>

<p>
    MyDailyFridge décrypte les code barres de vos produits
    alimentaires, analyse leur impact sur la santé mais surtout vous evites 
    les gachis alimentaire grâce à son système de notifications pour les dates limites de consommation !
</p>
<img  class ="image-display" alt="Logo" src="{{ asset('build/image_accueil.png') }}" width="(500)" height="300" >


<br/><br/><br/>
  <h2>Comment ça marche ?</h2>

<p>Pour utiliser gratuitement et en illimité l’application web “MyDailyFridge”, il suffit de créer un compte et vous aurez accès à ce dernier 24h/7j. </p>

Sur l’application MyDailyFridge vous avez accès aux pages:
<ol>
  <li><strong>Scanner :</strong> Cette page est dédiée pour scanner les codes barres des produits alimentaires afin d’obtenir les informations nutritionnelles.</li>
  <li><strong>Mes produits :</strong> Sur cette page vous trouverez l’ensemble des produits que vous avez scanner précédemment (historique).</li>
  <li><strong>Mon Frigo :</strong> Via cette page vous aurez la visibilité sur les produits alimentaires (scanner) présent dans votre frigo.</li>
  <li><strong>Mes produits périmés :</strong> Cette page liste les produits périmés que vous aviez scannés auparavant.</li>
</ol>


L'équipe MyDailyFridge vous souhaite une bonne visite !

 






{% endblock %}

{% block javascripts %}

    <script>
        const url = new URL('http://localhost:3000/.well-known/mercure');
        url.searchParams.append('topic', 'http://monsite.com/ping');
        

        const eventSource = new EventSource(url);
        eventSource.onmessage = event => {
            console.log(JSON.parse(event.data));
        }
    </script>




{% endblock %}

templates/daily_fridge/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DailyFridgeController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Symphony/DailyFridge/src/Controller/DailyFridgeController.php'|file_link(0) }}">src/Controller/DailyFridgeController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Symphony/DailyFridge/templates/daily_fridge/index.html.twig'|file_link(0) }}">templates/daily_fridge/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/daily_fridge/mon_frigo.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{# <br/>
<h3>Rechercher produit</h3>

    <div class="form-group">
    {% form_theme searchForm 'bootstrap_4_layout.html.twig' %}
    {{ form_start(searchForm) }}
    {{ form_row(searchForm.Nom, {'label': " ", 'attr': {'placeholder': 'Nom produit'}}) }}
    <button class="btn btn-primary">rechercher</button>
    {{ form_end(searchForm) }}

<br/> #}

<h2> Bienvenue sur la page mon frigo ! </h2><br/>


    <table class="table table-hover">
    <thead>
        <tr>
        <th scope="col">Désignation</th>
        <th scope="col">Marque</th>
        <th scope="col">Quantité</th>
        <th scope="col">Date d'achat</th>
        <th scope="col">Date de péremption</th>
        <th scope="col">Etat</th>
        </tr>
    </thead>
    <tbody>
    {% for Histoproduit in Histoproduits %}
        <tr class="table-light">
    
        <td>
        
            <div class="form-check">
                <label class="form-check-label">
                    <input class="form-check-input" type="checkbox" value="" checked="">
                         <a href="{{path('daily_fridge_Mon_Frigo_detail',{id: Histoproduit.produit.id })}}" > {{ Histoproduit.produit.nom }} </a>
                </label>
            </div>

        </td>
        <td>{{ Histoproduit.produit.marque }}</td>
        <td>{{ Histoproduit.quantite }}</td>
        <td>{{ Histoproduit.DateAchat | date('d/m/Y') }}</td>
        <td>{{ Histoproduit.datelimite | date('d/m/Y') }}</td>
        <td>
             {% if  (Histoproduit.DateLimite|date("m/d/Y") < "now"|date("m/d/Y"))  %}
                <a href="{{path('daily_fridge_Mon_Frigo_update_perimer',{id: Histoproduit.produit.id })}}" class="btn btn-danger delete-produit" >Attention A Ejecter</a>
                           
            {% else %}
                
                <a href="{{path('daily_fridge_Mon_Frigo_update_consommer',{id: Histoproduit.produit.id })}}"  class="btn btn-success consommer-produit"  >Consommer</a>
            {% endif %}
        </td>
    {% endfor %}
        </tr>
    </tbody>
    </table> 

    {{ knp_pagination_render(Histoproduits) }}

    {# <button type="submit" class="btn btn-primary">Recette</button> #}


{% endblock %}

templates/daily_fridge/mon_frigo_detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{# <br/>
<h3>Rechercher produit</h3>

    <div class="form-group">
    {% form_theme searchForm 'bootstrap_4_layout.html.twig' %}
    {{ form_start(searchForm) }}
    {{ form_row(searchForm.Nom, {'label': " ", 'attr': {'placeholder': 'Nom produit'}}) }}
    <button class="btn btn-primary">rechercher</button>
    {{ form_end(searchForm) }}

<br/> #}

<h2> Bienvenue sur la page mon frigo ! </h2><br/>


    <table class="table table-hover">
    <thead>
        <tr>
        <th scope="col">Désignation</th>
        <th scope="col">Marque</th>
        <th scope="col">Quantité</th>
        <th scope="col">Date d'achat</th>
        <th scope="col">Date de péremption</th>
        <th scope="col">Etat</th>
        </tr>
    </thead>
    <tbody>
    {% for Histoproduit in Histoproduits %}
        <tr class="table-light">
    
        <td>
            <div class="form-check">
                <label class="form-check-label">
                    <input class="form-check-input" type="checkbox" value="" checked="">
                        <a href="{{path('daily_fridge_Mon_Frigo_detail',{id: Histoproduit.produit.id })}}" > {{ Histoproduit.produit.nom }} </a>
                </label>
            </div>

             

        </td>
        <td>{{ Histoproduit.produit.marque }} </td>
        <td>{{ Histoproduit.quantite }}</td>
        <td>{{ Histoproduit.DateAchat | date('d/m/Y') }}</td>
        <td>{{ Histoproduit.datelimite | date('d/m/Y') }}</td>
        <td>
             {% if  (Histoproduit.DateLimite|date("m/d/Y") < "now"|date("m/d/Y"))  %}
                <a href="{{path('daily_fridge_Mon_Frigo_update_perimer',{id: Histoproduit.produit.id })}}" class="btn btn-danger delete-produit" >Attention A Ejecter</a>
                           
            {% else %}
                
                <a href="{{path('daily_fridge_Mon_Frigo_update_consommer',{id: Histoproduit.produit.id })}}"  class="btn btn-success consommer-produit"  >Consommer</a>
            {% endif %}
        </td>
    {% endfor %}
        </tr>
    </tbody>
    </table> 

    

    {# {% if  produit.id != 0  %}
             
        {{ produit.marque }}

    {% endif %} #}

    {# <button type="submit" class="btn btn-primary">Recette</button> #}

    <div class="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

    {% for produit in produit %}

        
        {# <div class="card border-primary mb-3" style="max-width: 20rem;">
        <div class="card-header">{{ produit.Nom }}</div>
        <div class="card-body">
        
        
            <h4>Nutricore :  
            {% if produit.nutriscoreGrade == 'e'  %}    
            <font color="red">{{ produit.nutriscoreGrade |capitalize }}</font>
            {% elseif produit.nutriscoreGrade == 'd'  %} 
            <font color="orange">{{ produit.nutriscoreGrade |capitalize }}</font>
            {% elseif produit.nutriscoreGrade == 'c'  %} 
            <font color="yellow">{{ produit.nutriscoreGrade |capitalize }}</font>
            {% elseif produit.nutriscoreGrade == 'b' %} 
            <font color="green">{{ produit.nutriscoreGrade |capitalize }}</font>
            {% elseif produit.nutriscoreGrade == 'a'  %} 
            <font color="green">{{ produit.nutriscoreGrade |capitalize }}</font>
            {% else %} 
            {{ 'Pas noté !'}}
            {% endif %} 

            </h4>  
        <br/>

        <h4> Les + </h4>
        
        {% if  (produit.TauxProteine != 0) and (produit.TauxProteine != 'undefined' ) %}
            
            <ul>
                <li>Taux de proteine : {{ produit.TauxProteine }} g</li>
            </ul>

        {% endif %}
        
        {% if  (produit.TauxFibre != 0)  and (produit.TauxFibre != 'undefined' ) %}

            <ul>
                <li>Taux de fibre : {{ produit.TauxFibre }} g</li>
            </ul>
        
        {% endif %}

        {% if  (produit.TauxEnergie != 0)  and (produit.TauxEnergie != 'undefined' ) %}  

            <ul>
                <li>Taux Energie : {{ produit.TauxEnergie }} g</li>

            </ul>

        {% endif %}
        
        {% if  (produit.tauxcalcium != 0)  and (produit.tauxcalcium != 'undefined' ) %}  

            <ul>
                <li>Taux Calcium : {{ produit.tauxcalcium }} g</li>

            </ul>

        {% endif %}
        {% if  (produit.tauxsodium != 0)  and (produit.tauxsodium != 'undefined' ) %}  

            <ul>
                <li>Taux Sodium : {{ produit.tauxsodium }} g</li>

            </ul>

        {% endif %}

        <h4> Les - </h4>
        
        {% if  (produit.TauxSel  != 0 ) and (produit.TauxSel != 'undefined' ) %}
            
            <ul>

                <li> Taux de sel :  {{ produit.TauxSel }} g</li>

            </ul>

        {% endif %} 

        {% if  (produit.TauxSucre != 0 ) and (produit.TauxSucre != 'undefined' ) %}

            <ul>
                
                <li> Taux de sucre :  {{ produit.TauxSucre }} g</li>
            
            </ul>

        {% endif %} 

        {% if  (produit.TauxGras != 0 ) and (produit.TauxGras != 'undefined' ) %} 

            <ul>
                
                <li>Taux de gras : {{ produit.TauxGras }} g</li>
            
            </ul>
        {% endif %} 

        {% if  (produit.TauxAdditif != 0 ) and (produit.TauxAdditif != 'undefined' )  %}

            <ul>
                
                <li>Taux d'additif : {{ produit.TauxAdditif }} g</li>

            </ul>
        {% endif %} 
           
        </div>
        </div>

         <img  class ="image-display" alt="Logo" src="{{ asset('build/Nutriscore.png') }}" width="(300)" height="200" >
        <p>
            Le Nutri-Score, grâce à une lettre et à une couleur, informe les consommateurs sur la qualité nutritionnelle d’un produit. 
            Chaque produit est ainsi positionné sur une échelle à 5 niveaux allant :
        </p>

        <ul>
            <li>du produit  le plus favorable sur le plan nutritionnel (classé A) </li>
        </ul>

        <ul>
            <li>au produit le moins favorable sur le plan nutritionnel (classé E) </li>
        </ul>

        <p> Ref : www.mangerbouger.fr</p> #}

        <div class="container">
            <div class="float-left">
                

                    <h4>Nutricore :  
                {% if produit.nutriscoreGrade == 'e'  %}    
                <font color="red">{{ produit.nutriscoreGrade |capitalize }}</font>
                {% elseif produit.nutriscoreGrade == 'd'  %} 
                <font color="orange">{{ produit.nutriscoreGrade |capitalize }}</font>
                {% elseif produit.nutriscoreGrade == 'c'  %} 
                <font color="yellow">{{ produit.nutriscoreGrade |capitalize }}</font>
                {% elseif produit.nutriscoreGrade == 'b' %} 
                <font color="green">{{ produit.nutriscoreGrade |capitalize }}</font>
                {% elseif produit.nutriscoreGrade == 'a'  %} 
                <font color="green">{{ produit.nutriscoreGrade |capitalize }}</font>
                {% else %} 
                {{ 'Pas noté !'}}
                {% endif %} 

                </h4>  
                <br/>

                <h4> Les + </h4>
                
                {% if  (produit.TauxProteine != 0) and (produit.TauxProteine != 'undefined' ) %}
                    
                    <ul>
                        <li>Taux de proteine : {{ produit.TauxProteine }} g</li>
                    </ul>

                {% endif %}
                
                {% if  (produit.TauxFibre != 0)  and (produit.TauxFibre != 'undefined' ) %}

                    <ul>
                        <li>Taux de fibre : {{ produit.TauxFibre }} g</li>
                    </ul>
                
                {% endif %}

                {% if  (produit.TauxEnergie != 0)  and (produit.TauxEnergie != 'undefined' ) %}  

                    <ul>
                        <li>Taux Energie : {{ produit.TauxEnergie }} g</li>

                    </ul>

                {% endif %}
                
                {% if  (produit.tauxcalcium != 0)  and (produit.tauxcalcium != 'undefined' ) %}  

                    <ul>
                        <li>Taux Calcium : {{ produit.tauxcalcium }} g</li>

                    </ul>

                {% endif %}
                {% if  (produit.tauxsodium != 0)  and (produit.tauxsodium != 'undefined' ) %}  

                    <ul>
                        <li>Taux Sodium : {{ produit.tauxsodium }} g</li>

                    </ul>

                {% endif %}

                <h4> Les - </h4>
                
                {% if  (produit.TauxSel  != 0 ) and (produit.TauxSel != 'undefined' ) %}
                    
                    <ul>

                        <li> Taux de sel :  {{ produit.TauxSel }} g</li>

                    </ul>

                {% endif %} 

                {% if  (produit.TauxSucre != 0 ) and (produit.TauxSucre != 'undefined' ) %}

                    <ul>
                        
                        <li> Taux de sucre :  {{ produit.TauxSucre }} g</li>
                    
                    </ul>

                {% endif %} 

                {% if  (produit.TauxGras != 0 ) and (produit.TauxGras != 'undefined' ) %} 

                    <ul>
                        
                        <li>Taux de gras : {{ produit.TauxGras }} g</li>
                    
                    </ul>
                {% endif %} 

                {% if  (produit.TauxAdditif != 0 ) and (produit.TauxAdditif != 'undefined' )  %}

                    <ul>
                        
                        <li>Taux d'additif : {{ produit.TauxAdditif }} g</li>

                    </ul>
                {% endif %} 






            </div>
            <div class="float-right">
                
                <img  class ="image-display" alt="Logo" src="{{ asset('build/Nutriscore_2.png') }}" width="(300)" height="200" >
                {# <p>
                    Le Nutri-Score, grâce à une lettre et à une couleur, informe les consommateurs sur la qualité nutritionnelle d’un produit. 
                    Chaque produit est ainsi positionné sur une échelle à 5 niveaux allant :
                </p>

                <ul>
                    <li>du produit  le plus favorable sur le plan nutritionnel (classé A) </li>
                </ul>

                <ul>
                    <li>au produit le moins favorable sur le plan nutritionnel (classé E) </li>
                </ul>
     #} 
                   
                <p>
                    Le Nutri-Score, grâce à une lettre et à une couleur, </br>
                    informe les consommateurs sur la qualité nutritionnelle d’un produit. </br>
                    Chaque produit est ainsi positionné sur une échelle à 5 niveaux allant :
                </p>

                <ul>
                    <li>du produit le plus favorable sur le plan nutritionnel (classé A) </li>
                </ul>

                <ul>
                    <li>au produit le moins favorable sur le plan nutritionnel (classé E) </li>
                </ul>

                <p> Ref : www.mangerbouger.fr</p> 
            </div>
            

        </div>
        </br></br></br></br></br></br></br></br></br></br></br></br></br>
        
    {% endfor %}
{% endblock %}